name: capybara_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management
  provider: ^5.0.0
  
  # dependency injection
  get_it: ^7.2.0

  # Value equality for reference types
  equatable: ^2.0.3

  # Functional programming, eg. "Either" type
  dartz: ^0.10.0

  # Remote API
  internet_connection_checker: ^0.0.1+2
  dio: ^4.0.0
  google_sign_in: ^5.0.7

  # Local cache
  shared_preferences: ^2.0.6

  # Validators
  form_field_validator: ^1.1.0

  # GetX
  get: ^4.3.8

  # Reactive extensions for Dart
  rxdart: ^0.27.1

  # SVG
  flutter_svg: ^0.22.0
  pretty_dio_logger: ^1.2.0-beta-1
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter 

  # Mock testing
  mocktail: ^0.1.4
  http_mock_adapter: ^0.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
          weight: 300
      
